spring:
  datasource:
    url: ${GUEST_PROFILE_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
    locations: classpath:db/migration
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL}
    sender:
      type: web
  jpa:
    hibernate:
      ddl-auto: update   
  kafka:
    consumer:
      topic: ${KAFKA_TOPIC}
      bootstrap-servers: ${KAFKA_SERVER}
      auto-offset-reset: earliest
      group-id: reservation_system
      key-deserializer: com.incubator.dbs.guestservice.model.template.deserializer.CreateGuestDeserializer
      value-deserializer: com.incubator.dbs.guestservice.model.template.deserializer.CreateGuestDeserializer      
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}
  instance:
    hostName: ${EUREKA_INSTANCE_HOST}
server:
  port: 9082

springdoc:
  swagger-ui:
    path: /swagger-ui.html